#:schema node_modules/wrangler/config-schema.json
name = "sublink-worke"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "de83a052428d450baf68bf80a7dc78d6" }
]

[assets]
directory = "./public"
